### ISSUE TITLE
Bug: Speki closes unexpectedly when pressing 'Del'

### ISSUE THREAD

**Issue by Xylol** [TBS1996/speki#13]
What is the bug:
If you are in the 'Add card' tab in the 'insert mode' pane and press 'Del'-Key then sometimes speki closes unexpectedly.

How to reproduce:
* Open windows version 'v0.1.6 Windows_x64'
* Press Tab
* Type 'aa' (single character is not enough)
* Press the 'Del' (above arrow keys) key.

**Comment by TBS1996** [comment]
Thanks for notifying me! I uploaded a fix now, could you check if it works?

**Comment by Xylol** [comment]
Fixed. (Thank you for the nice product, the time you spent and sharing it)
