### ISSUE TITLE
Manually added cards do not show up on Review

### ISSUE THREAD

**Issue by yigitsever** [TBS1996/speki#15]
Hello,

I can't seem to manually add cards for review

Steps I follow;

- `tab` to Add card tab
- Fill both textboxes
- `alt-f` to save
- `s-tab` to Review tab

The cards I add do not show up on there, I tried `alt-r` to refresh too

The decks I import from anki do show up

I looked around the source code and the database (`dbflash.db`) a bit and realized that new cards are added with `CardType::Finished`

https://github.com/TBS1996/speki/blob/d1f0ad26049837f9ea79c3e7a1a197eb786282a0/src/tabs/add_card/logic.rs#L103-L116

I changed the `CardType::Finished` to `CardType::Pending` and manually added cards started to show up on review

However, I'm not familiar with the logic of the rest of the program so I'm not sure whether this fix is correct

**Comment by TBS1996** [comment]
oh yeah.. they won't show up until a day! in the start they have an interval of 1 day, and they will show up on review when they are at 90% recall-chance.

if you want to inspect the recall-chance (strength) of cards then you can open up the database with "DB browser for sqlite"

**Comment by yigitsever** [comment]
ok thank you for clarifying, guess I was confused because there isn't a browser for added cards, guess that's already on the future plans

**Comment by TBS1996** [comment]
yes its definitively in the works! if you look at the code you can see it's already in development

**Comment by TBS1996** [comment]
> ok thank you for clarifying, guess I was confused because there isn't a browser for added cards, guess that's already on the future plans

Merhaba,

try updating now! I've added a rudimentary browser tab. Will be improved upon of course.
