### ISSUE TITLE
Fedora 37, Speki doesn't work

### ISSUE THREAD

**Issue by SatanEd** [TBS1996/speki#18]
**Fedora 37, Installation with Cargo**

I installed Speki with Cargo and when I run Speki:
`speki: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`
But it seems like it's in place:
`Package openssl1.1-1:1.1.1q-2.fc37.i686 is already installed.`

**Comment by SatanEd** [comment]
Solved by
`sudo dnf install alsa-lib-devel

`

**Comment by TBS1996** [comment]
Thank you! I'll put this in the README :)
