### ISSUE TITLE
Installation. [Cargo; windows 10; link]

### ISSUE THREAD

**Issue by PFAhard** [TBS1996/speki#6]
Probably not directly related to the crate, but maybe someone knows the solution.

```error
  = note: LINK : fatal error LNK1181: cannot open input file 'sqlite3.lib'


error: could not compile `speki` due to previous error
```
I tried downloading the library and binary, and running cargo install from that directory, but it didn't work.

**Comment by TBS1996** [comment]
hmm yeah, I need to figure this one out. In the mean time there's a possible fix here: https://stackoverflow.com/questions/59648046/unable-to-compile-rust-program-lnk1181-cannot-open-input-file-c-program-obj

I'm looking into github actions now to see if I can make github compile it automatically for windows, hopefully windows users could simply run such a binary and it would work. I'm figuring things out as i go along here

**Comment by TBS1996** [comment]
Hey, I added a binary now for windows, could you check if it works for you?

**Comment by PFAhard** [comment]
Yes, it works perfectly.

**Comment by TBS1996** [comment]
that's great!
