### ISSUE TITLE
Missing boundcheck for `self.cursor.row` in `textinput.rs` causes panic

### ISSUE THREAD

**Issue by geri1701** [TBS1996/speki#9]
If a new topic is created and the entry made is removed with backspace, a panic occurs.
`thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0' src/utils/widgets/textinput.rs:459:12`

**Comment by TBS1996** [comment]
Thanks a lot! I fixed it now, I need to clean up the textinput code but for now a quickfix worked.

It'll go live in 0.1.17
